services:
  mysql:
    container_name: mysql
    image: mysql:8.3
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=${DB_PASS}
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    container_name: bookstack
    image: solidnerd/bookstack:24.10.2
    depends_on:
    - mysql
    env_file: "bookstack.env"
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=${DB_PASS}
    #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
    - APP_URL=${APP_URL}
    # APP_KEY is used for encryption where needed, so needs to be persisted to
    # preserve decryption abilities.
    # Can run `php artisan key:generate` to generate a key
    - APP_KEY=${APP_KEY}
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - ${PORT}:8080

volumes:
 mysql-data:
 uploads:
 storage-uploads: